language: python
python:
    - 2.6
    - 2.7
    # comment out pypy until travis updates to pypy 2.0/2.1, cffi doesn't work
    # on PyPy 1.9
    # - pypy
env:
    - REACTOR=select ZMQ_VERSION=2
    - REACTOR=epoll ZMQ_VERSION=2
    - REACTOR=epoll ZMQ_VERSION=3
    - REACTOR=epoll ZMQ_VERSION=3
install:
    - test "$ZMQ_VERSION" == "3" && sudo apt-get install libzmq3-dev || true
    - test "$ZMQ_VERSION" == "2" && sudo apt-get remove libzmq3 && sudo apt-get install libzmq-dev || true
    - pip install -r requirements.txt --use-mirrors
script:
    - trial --reactor=$REACTOR txzmq
    - pep8 --repeat txzmq
    - pyflakes txzmq
notifications:
    email:
        - me@smira.ru
