language: python
python:
    - 2.6
    - 2.7
    - pypy
env:
    - REACTOR=select
    - REACTOR=epoll
install:
    - sudo apt-get install libzmq3-dev
    - pip install -r requirements.txt --use-mirrors
script:
    - trial --reactor=$(REACTOR) txzmq
    - pep8 --repeat txzmq
    - pyflakes txzmq
notifications:
    email:
        - me@smira.ru
