language: python
python:
    - 2.6
    - 2.7
    - 3.3
    # comment out pypy until travis updates to pypy 2.0/2.1, cffi doesn't work
    # on PyPy 1.9
    # - pypy
env:
    - REACTOR=select
    - REACTOR=epoll
install:
    - sudo apt-get install libzmq3-dev
    - pip install -r requirements.txt --use-mirrors
script:
    - coverage run $VIRTUAL_ENV/bin/trial --reactor=$REACTOR txzmq
    - pep8 --repeat txzmq
    - pyflakes txzmq
after_success:
    - coveralls
notifications:
    email:
        - me@smira.ru
