language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy
    - pypy3
env:
    - REACTOR=select
    - REACTOR=epoll
install:
    - sudo apt-get install libzmq3-dev
    - pip install -r requirements.txt --use-mirrors
script:
    - >-
        [ ! -f $VIRTUAL_ENV/bin/trial ] || coverage run $VIRTUAL_ENV/bin/trial --reactor=$REACTOR txzmq
    - pep8 --repeat txzmq
    - pyflakes txzmq
    - python examples/integration_test.py
after_success:
    - coveralls
notifications:
    email:
        - me@smira.ru
matrix:
    allow_failures:
        - python: pypy
        - python: pypy3
