language: python
python:
    - 2.6
    - 2.7
    - pypy
env:
    - REACTOR=select
    - REACTOR=epoll
install:
    - sudo apt-get install libzmq3-dev
    - make env
script:
    - make test
    - make check
notifications:
    email:
        - me@smira.ru
